kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-controller
subjects:
- kind: ServiceAccount
  name: secret-sync-controller-sa
  namespace: secret-sync-controller
roleRef:
  kind: ClusterRole
  name: secret-sync-controller
  apiGroup: rbac.authorization.k8s.io
