name: create release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: |
        .ci/tag-from-ref.sh "${GITHUB_REF}"
    - name: Publish Docker Image to Github packages
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        IMAGE_NAME: 'secret-sync-controller'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'
        TAG: ${{ steps.get_version.outputs.TAG }}
